[package]
name = "bilibili_music"
version = "0.1.0"
authors = ["jackpot <wikileaks928@gmail.com>"]
edition = "2021"

[dependencies]
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.125"
ureq = "2.10.1"
