[type.rust]
binary = false
check-filename = true
check-file = true
unicode = true
ignore-hex = true
identifier-leading-digits = false
locale = "en-us"
extend-ignore-identifiers-re = []
extend-ignore-words-re = []
extend-ignore-re = []